"""Documentation must never point at a file that does not exist.

Catches the drift that happens when files are renamed or removed but the
README still references them — which is how a reviewer following the docs
ends up at a dead end.

Glob patterns (scripts/*.sh) and command fragments are skipped: they are
instructions, not links.
"""
import os
import re
import sys

os.chdir(os.path.join(os.path.dirname(__file__), ".."))

# docs/PHASE5_PLAN.md is deliberately NOT here yet: it names files that
# Phase 5 has not created (helm/observability/, grafana/dashboards/,
# docs/runbooks/), so scanning it now would fail on work that has not
# happened. Add it in W15, once those paths exist.
DOCS = ["README.md", "evidence/README.md"]
# Backticked paths that look like real files in our tree
PATH_RE = re.compile(r'`((?:scripts|jenkins|docs|tests|terraform|helm|app|docker)/[\w./-]+)`')
LINK_RE = re.compile(r'\[[^\]]*\]\(([^)]+)\)')

# Files the reader is told to CREATE, so they legitimately do not exist in a
# fresh checkout. Each must have a committed .example counterpart, which is
# checked below — that is what stops this list becoming a way to hide typos.
USER_CREATED = {
    "terraform/terraform.tfvars": "terraform/terraform.tfvars.example",
    "terraform/backend.tf": None,          # generated by bootstrap-state.sh
}

bad = []
for created, example in USER_CREATED.items():
    if example and not os.path.exists(example):
        bad.append(f"{created} is documented but its example file {example} is missing")
for doc in DOCS:
    if not os.path.exists(doc):
        bad.append(f"missing document: {doc}")
        continue
    body = open(doc).read()

    for path in LINK_RE.findall(body):
        path = path.split("#")[0].strip()
        if not path or path.startswith(("http", "mailto:")):
            continue
        target = path if doc == "README.md" else os.path.join(os.path.dirname(doc), path)
        if path in USER_CREATED:
            continue
        if not os.path.exists(target) and not os.path.exists(path):
            bad.append(f"{doc}: broken link -> {path}")

    for path in PATH_RE.findall(body):
        if "*" in path or path.endswith("/") or path in USER_CREATED:
            continue        # a glob, a directory, or a file the user creates
        if not os.path.exists(path):
            bad.append(f"{doc}: references missing file -> {path}")

if bad:
    print("\n".join(sorted(set(bad))))
    sys.exit(1)
print(f"all documentation references resolve ({len(DOCS)} documents checked)")
