#!/bin/bash
# bootstrap-state.sh
# ONE-TIME setup for remote Terraform state (review fix, Priority 4).
#
# Why a separate script? Terraform cannot create the S3 bucket that stores
# its own state (chicken-and-egg problem), so the bucket and the DynamoDB
# lock table are created here with the AWS CLI, then backend.tf is
# generated and existing local state is migrated to S3.
#
# Usage: ./bootstrap-state.sh
set -e

AWS_REGION="${AWS_REGION:-us-east-1}"
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
STATE_BUCKET="vm-order-terraform-state-${ACCOUNT_ID}"   # account ID = globally unique
LOCK_TABLE="vm-order-terraform-locks"

echo "============================================"
echo "  Remote State Bootstrap"
echo "============================================"
echo "Region:      $AWS_REGION"
echo "State bucket: $STATE_BUCKET"
echo "Lock table:   $LOCK_TABLE"
echo ""

# --- 1. S3 bucket (versioned + encrypted + private) ---
if aws s3api head-bucket --bucket "$STATE_BUCKET" 2>/dev/null; then
    echo "✅ State bucket already exists"
else
    echo "Creating state bucket..."
    if [ "$AWS_REGION" == "us-east-1" ]; then
        aws s3api create-bucket --bucket "$STATE_BUCKET" --region "$AWS_REGION"
    else
        aws s3api create-bucket --bucket "$STATE_BUCKET" --region "$AWS_REGION" \
            --create-bucket-configuration LocationConstraint="$AWS_REGION"
    fi
    # Versioning — protects against accidental state corruption/deletion
    aws s3api put-bucket-versioning --bucket "$STATE_BUCKET" \
        --versioning-configuration Status=Enabled
    # Encryption at rest
    aws s3api put-bucket-encryption --bucket "$STATE_BUCKET" \
        --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
    # Block ALL public access — state contains sensitive values
    aws s3api put-public-access-block --bucket "$STATE_BUCKET" \
        --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true
    echo "✅ State bucket created (versioned, encrypted, private)"
fi

# --- 2. DynamoDB lock table (prevents concurrent terraform runs) ---
if aws dynamodb describe-table --table-name "$LOCK_TABLE" --region "$AWS_REGION" >/dev/null 2>&1; then
    echo "✅ Lock table already exists"
else
    echo "Creating DynamoDB lock table..."
    aws dynamodb create-table \
        --table-name "$LOCK_TABLE" \
        --attribute-definitions AttributeName=LockID,AttributeType=S \
        --key-schema AttributeName=LockID,KeyType=HASH \
        --billing-mode PAY_PER_REQUEST \
        --region "$AWS_REGION" >/dev/null
    aws dynamodb wait table-exists --table-name "$LOCK_TABLE" --region "$AWS_REGION"
    echo "✅ Lock table created"
fi

# --- 3. Generate backend.tf (backend blocks cannot use variables) ---
cat > backend.tf << BACKEND
# backend.tf — generated by bootstrap-state.sh
# Contains no credentials (bucket name, key, region, lock table only), but
# it IS gitignored: each contributor runs bootstrap-state.sh and gets their
# own uniquely-named bucket, so committing one person's file would send
# everyone else's state to the wrong place. Same reasoning as
# terraform.tfvars — per-contributor config, generated not shared.
terraform {
  backend "s3" {
    bucket         = "${STATE_BUCKET}"
    key            = "phase3/terraform.tfstate"
    region         = "${AWS_REGION}"
    dynamodb_table = "${LOCK_TABLE}"
    encrypt        = true
  }
}
BACKEND
echo "✅ backend.tf generated"

# --- 4. Migrate existing local state to S3 ---
echo ""
echo "Migrating state to S3 (answer 'yes' when asked)..."
terraform init -migrate-state

echo ""
echo "✅ Remote state is now active! Local terraform.tfstate can be deleted"
echo "   after verifying: terraform state list"
