apiVersion: v2
name: backend
description: VM Order Portal — backend API service (Flask)
type: application
version: 0.1.0        # chart version
appVersion: "1.0.0"   # image version it deploys by default
